version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: crudWithRedisMongo_container
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis_stack_container
    ports:
      - "6379:6379"   # Redis server
      - "8001:8001"   # Redis Stack Browser UI
    restart: unless-stopped

volumes:
  mongo_data: