server:
  port: 8081
spring:
  application:
    name: crud-with-redis
  cache:
    type: redis
  data:
    mongodb:
      port: 27017
      host: localhost
      database: crudWithRedis
    redis:
      port: 6379
      host: localhost
      timeout: 2000
      jedis:
        pool:
          max-active: 128

logging:
  level:
    root: info
    org.springframework.data.redis: debug
    org.springframework.data.mongodb.core.MongoTemplate: debug